### PR TITLE
Exceptions refactoring [with logging code clean]

### LINKED ISSUE #170: Refactor Exceptions and logging

### PR DESCRIPTION
**Pull request by Jadw1**
Resolves #170

### CODE REVIEW

File: prinz_h2o/src/main/scala/pl/touk/nussknacker/prinz/h2o/model/H2OModelInstance.scala [hunk 1]
```diff
@@ -56,7 +49,7 @@ case class H2OModelInstance(private val modelWrapper: EasyPredictModelWrapper,
     case ModelCategory.KLime            => p.asInstanceOf[KLimeModelPrediction].cluster
     case ModelCategory.CoxPH            => p.asInstanceOf[CoxPHModelPrediction].value
     case ModelCategory.Regression       => p.asInstanceOf[RegressionModelPrediction].value
-    case _ => throw new ModelRunException(s"ModelCategory $modelCategory not supported.")
+    case _ => throw new ModelRunException(new Exception(s"ModelCategory $modelCategory not supported."))
```
Comment (avan1235) [inline prinz_h2o/src/main/scala/pl/touk/nussknacker/prinz/h2o/model/H2OModelInstance.scala]: don't create Exception class instance as they don't tell anything. Maybe InvalidStateException or InvalidArgumentExcptio here would be suitable?

Comment (avan1235) [reply prinz_h2o/src/main/scala/pl/touk/nussknacker/prinz/h2o/model/H2OModelInstance.scala]: also PrinzException supports creating the exption with only message so refactor ModelRunException to support also

File: prinz_util/src/main/scala/pl/touk/nussknacker/prinz/util/http/RestClientException.scala [hunk 2]
```diff
@@ -1,6 +1,10 @@
 package pl.touk.nussknacker.prinz.util.http
 
-final case class RestClientException(message: String) extends Exception {
+final case class RestClientException(cause: Throwable) extends Exception(cause) {
 
-  override def toString: String = s"${getClass.getSimpleName}: ${this.message}"
+  override def toString: String = s"${getClass.getSimpleName}: ${this.getMessage}"
+
+  def this(message: String) {
+    this(new Exception(message))
```
Comment (avan1235) [inline prinz_util/src/main/scala/pl/touk/nussknacker/prinz/util/http/RestClientException.scala:8]: It's not a good practice imo, not every exception has to have some other throwable as a cause. Try to call here the super constructor with only message (because there is a constructor in exception class that takes only String value)

File: prinz_util/src/main/scala/pl/touk/nussknacker/prinz/util/http/AsyncRestJsonClient.scala [hunk 3]
```diff
@@ -15,19 +16,18 @@ class AsyncRestJsonClient(baseUrl: String, private val backend: SttpBackend[Futu
...
                                  (implicit decoder: Decoder[RESPONSE]): Future[RestClientResponse[RESPONSE]] = {
     val request = createGetRequest(relativePath, params)
-    wrapCaughtException(
-      () => request.send(backend).map { response => response.body.left.map(clientExceptionFromResponse) },
-      e => Future(Left(RestClientException(e.getMessage)))
-    )
+    wrap(request)
   }
+
+  private def wrap[RESPONSE: Manifest]
```
Comment (avan1235) [inline prinz_util/src/main/scala/pl/touk/nussknacker/prinz/util/http/AsyncRestJsonClient.scala]: this is [wrap](https://cdn.mcdonalds.pl/uploads/20210423094031/01-15-mcwrap-klasyczny-singlepage-copy.png) XD Please fix the name to be more descriptive because it's not wrapping the request (or rather the request can be wrapped in a few ways, not only catching the exception but also proxying its headers etc.)

File: prinz_util/src/main/scala/pl/touk/nussknacker/prinz/util/http/AsyncRestJsonClient.scala [hunk 4]
```diff
@@ -15,19 +16,18 @@ class AsyncRestJsonClient(baseUrl: String, private val backend: SttpBackend[Futu
...
+    (request: RequestT[Identity, Either[ResponseException[String, circe.Error], RESPONSE], Any]) = wrapCaughtException(
```
Comment (avan1235) [inline prinz_util/src/main/scala/pl/touk/nussknacker/prinz/util/http/AsyncRestJsonClient.scala:29]: also check if this method cannot be merged with the wrapCaughtException because now we have two wrapping exceptions methods which looks unnecessary

File: prinz_util/src/main/scala/pl/touk/nussknacker/prinz/util/http/RestJsonClient.scala [hunk 5]
```diff
@@ -1,27 +1,28 @@
...
                                  (implicit decoder: Decoder[RESPONSE]): RestClientResponse[RESPONSE] = {
     val request = createGetRequest(relativePath, params)
-    wrapCaughtException(
-      () => request.send(backend).body.left.map(clientExceptionFromResponse),
-      e => Left(RestClientException(e.getMessage))
-    )
+    wrap(request)
   }
+
+  private def wrap[RESPONSE: Manifest]
```
Comment (avan1235) [inline prinz_util/src/main/scala/pl/touk/nussknacker/prinz/util/http/RestJsonClient.scala]: imo should be merge in AbstractRestJsonClient if possible with wrapCaughtException because now it looks like code duplication  (it was actually but now it is a separate method)

**Review by avan1235 — CHANGES_REQUESTED** [review]

**Review by kantoniak — DISMISSED** [review]
Could you include refactoring scope in the title?

File: prinz_util/src/main/scala/pl/touk/nussknacker/prinz/util/http/RestClientException.scala (hunk 2 above)
Comment (Jadw1) [reply prinz_util/src/main/scala/pl/touk/nussknacker/prinz/util/http/RestClientException.scala:8]: however in scala u only can call one of the super class' constructor and actually in code, we're creating RestClientException from other Exception. so calling the one that accepts only message, will make us to lost stack trace i think

File: prinz_util/src/main/scala/pl/touk/nussknacker/prinz/util/http/AbstractRestJsonClient.scala [hunk 6]
```diff
@@ -28,13 +31,19 @@ abstract class AbstractRestJsonClient(private val baseUrl: String) {
...
-    RestClientException(value.toString)
+    RestClientException(value)
 
   protected def wrapCaughtException[R](requestAction: () => R, exceptionHandler: Exception => R): R = try {
     requestAction()
   } catch {
     case e: SttpClientException => exceptionHandler(e)
   }
+
+  /*protected def defaultWrapCaughtException[RESPONSE: Manifest, F[_]]
```
Comment (Jadw1) [inline prinz_util/src/main/scala/pl/touk/nussknacker/prinz/util/http/AbstractRestJsonClient.scala]: I've trying to merge that 2 'wrapping' methods but I didn't manage to deal with 'cannot resolve symbol map' error. Maybe one of u have some idea?

Comment (avan1235) [reply prinz_util/src/main/scala/pl/touk/nussknacker/prinz/util/http/AbstractRestJsonClient.scala]: oh, I see now there is no chance to do as these clients are different because one returns Future and other the Identity of request. I changed the names of these functions that you introduced to make it visible why they are different

File: prinz_util/src/main/scala/pl/touk/nussknacker/prinz/util/http/RestClientException.scala (hunk 2 above)
Comment (avan1235) [reply prinz_util/src/main/scala/pl/touk/nussknacker/prinz/util/http/RestClientException.scala:8]: understood, btw I removed this constructor as it was used only by one exception that was not used (so also got removed)

**Comment by avan1235** [comment]
Looks good, imo you can merge it now 👍🏻

**Review by avan1235 — APPROVED** [review]
